ignore:
  - "application.go"  # nothing to see here ;)
  - "docs/**"  # nothing to see here ;)
  - "util/**"  # nothing to see here ;)
  - "model/**"  # nothing to see here ;)
  - "mem/**"  # nothing to see here ;)
  - "controller/**"  # nothing to see here ;)