ignore:
  - "model/**"          # nothing to see here ;)
  - "mem/**"            # nothing to see here ;)
  - "application.go"    # nothing to see here ;)
  - "util/keyboard.go"  # nothing to see here ;)
  - "util/socket.go"    # nothing to see here ;)
