
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "vbom.ml/util"

[[constraint]]
  branch = "master"
  name = "github.com/Jeffail/gabs"

[prune]
  go-tests = true
  unused-packages = true
